/*
White Label Communications CPaas API Documentation

Testing ChannelAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ChannelAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ChannelAPIService V1AccountAccountIDChannelChannelIDGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string
		var channelID string

		resp, httpRes, err := apiClient.ChannelAPI.V1AccountAccountIDChannelChannelIDGet(context.Background(), accountID, channelID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChannelAPIService V1AccountAccountIDChannelChannelIDPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string
		var channelID string

		resp, httpRes, err := apiClient.ChannelAPI.V1AccountAccountIDChannelChannelIDPost(context.Background(), accountID, channelID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChannelAPIService V1AccountAccountIDChannelChannelIDPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string
		var channelID string

		resp, httpRes, err := apiClient.ChannelAPI.V1AccountAccountIDChannelChannelIDPut(context.Background(), accountID, channelID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChannelAPIService V1AccountAccountIDChannelGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string

		resp, httpRes, err := apiClient.ChannelAPI.V1AccountAccountIDChannelGet(context.Background(), accountID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChannelAPIService V1AccountAccountIDDeviceDeviceIDChannelGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string
		var deviceID string

		resp, httpRes, err := apiClient.ChannelAPI.V1AccountAccountIDDeviceDeviceIDChannelGet(context.Background(), accountID, deviceID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChannelAPIService V1AccountAccountIDUserUserIDChannelGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string
		var userID string

		resp, httpRes, err := apiClient.ChannelAPI.V1AccountAccountIDUserUserIDChannelGet(context.Background(), accountID, userID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
