/*
White Label Communications CPaas API Documentation

Testing WebhookAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_WebhookAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WebhookAPIService V1WebhookAccountAccountIDGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string

		resp, httpRes, err := apiClient.WebhookAPI.V1WebhookAccountAccountIDGet(context.Background(), accountID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService V1WebhookAccountAccountIDPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string

		resp, httpRes, err := apiClient.WebhookAPI.V1WebhookAccountAccountIDPost(context.Background(), accountID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService V1WebhookAccountAccountIDWebhookIDDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string
		var webhookID int32

		resp, httpRes, err := apiClient.WebhookAPI.V1WebhookAccountAccountIDWebhookIDDelete(context.Background(), accountID, webhookID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService V1WebhookAccountAccountIDWebhookIDGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string
		var webhookID int32

		resp, httpRes, err := apiClient.WebhookAPI.V1WebhookAccountAccountIDWebhookIDGet(context.Background(), accountID, webhookID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService V1WebhookAccountAccountIDWebhookIDPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountID string
		var webhookID int32

		resp, httpRes, err := apiClient.WebhookAPI.V1WebhookAccountAccountIDWebhookIDPut(context.Background(), accountID, webhookID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
