/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapi;

import java.util.Objects;
import java.util.Arrays;
import bytes;
import fmt;

/**
 * ServiceVOIPMediaAddEditData
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.GoClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceVOIPMediaAddEditData {
  @.annotation.Nullable
  private string Description;

  /**
   * Gets or Sets MediaSource
   */
  public enum MEDIA_SOURCE {
    UPLOAD(string.valueOf("upload")),
    
    RECORDING(string.valueOf("recording")),
    
    TTS(string.valueOf("tts"));

    private string value;

    MEDIA_SOURCE(string value) {
      this.value = value;
    }

    public string getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MEDIA_SOURCE fromValue(string value) {
      for (MEDIA_SOURCE b : MEDIA_SOURCE.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @.annotation.Nullable
  private MEDIA_SOURCE MediaSource;

  @.annotation.Nonnull
  private string Name;

  @.annotation.Nullable
  private ServiceTTS Tts;

  public ServiceVOIPMediaAddEditData() {
  }

  public ServiceVOIPMediaAddEditData Description(@.annotation.Nullable string Description) {
    
    this.Description = Description;
    return this;
  }

  /**
   * Get Description
   * @return Description
   */
  @.annotation.Nullable

  public string GetDescription() {
    return Description;
  }


  public void setDescription(@.annotation.Nullable string Description) {
    this.Description = Description;
  }

  public ServiceVOIPMediaAddEditData MediaSource(@.annotation.Nullable MEDIA_SOURCE MediaSource) {
    
    this.MediaSource = MediaSource;
    return this;
  }

  /**
   * Get MediaSource
   * @return MediaSource
   */
  @.annotation.Nullable

  public MEDIA_SOURCE GetMediaSource() {
    return MediaSource;
  }


  public void setMediaSource(@.annotation.Nullable MEDIA_SOURCE MediaSource) {
    this.MediaSource = MediaSource;
  }

  public ServiceVOIPMediaAddEditData Name(@.annotation.Nonnull string Name) {
    
    this.Name = Name;
    return this;
  }

  /**
   * Get Name
   * @return Name
   */
  @.annotation.Nonnull

  public string GetName() {
    return Name;
  }


  public void setName(@.annotation.Nonnull string Name) {
    this.Name = Name;
  }

  public ServiceVOIPMediaAddEditData Tts(@.annotation.Nullable ServiceTTS Tts) {
    
    this.Tts = Tts;
    return this;
  }

  /**
   * Get Tts
   * @return Tts
   */
  @.annotation.Nullable

  public ServiceTTS GetTts() {
    return Tts;
  }


  public void setTts(@.annotation.Nullable ServiceTTS Tts) {
    this.Tts = Tts;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPMediaAddEditData ServiceVOIPMediaAddEditData = (ServiceVOIPMediaAddEditData) o;
    return Objects.equals(this.Description, ServiceVOIPMediaAddEditData.Description) &&
        Objects.equals(this.MediaSource, ServiceVOIPMediaAddEditData.MediaSource) &&
        Objects.equals(this.Name, ServiceVOIPMediaAddEditData.Name) &&
        Objects.equals(this.Tts, ServiceVOIPMediaAddEditData.Tts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Description, MediaSource, Name, Tts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPMediaAddEditData {\n");
    sb.append("    Description: ").append(toIndentedString(Description)).append("\n");
    sb.append("    MediaSource: ").append(toIndentedString(MediaSource)).append("\n");
    sb.append("    Name: ").append(toIndentedString(Name)).append("\n");
    sb.append("    Tts: ").append(toIndentedString(Tts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

