/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapi;

import java.util.Objects;
import java.util.Arrays;
import bytes;
import fmt;

/**
 * ServiceVOIPAccountEditData
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.GoClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceVOIPAccountEditData {
  @.annotation.Nullable
  private ServiceVOIPAccountCallRecording CallRecording;

  @.annotation.Nullable
  private ServiceVOIPSharedDoNotDisturb DoNotDisturb;

  @.annotation.Nullable
  private bool Enabled;

  @.annotation.Nullable
  private ServiceVOIPAccountMusicOnHold MusicOnHold;

  @.annotation.Nonnull
  private string Name;

  @.annotation.Nonnull
  private string Timezone;

  public ServiceVOIPAccountEditData() {
  }

  public ServiceVOIPAccountEditData CallRecording(@.annotation.Nullable ServiceVOIPAccountCallRecording CallRecording) {
    
    this.CallRecording = CallRecording;
    return this;
  }

  /**
   * Get CallRecording
   * @return CallRecording
   */
  @.annotation.Nullable

  public ServiceVOIPAccountCallRecording GetCallRecording() {
    return CallRecording;
  }


  public void setCallRecording(@.annotation.Nullable ServiceVOIPAccountCallRecording CallRecording) {
    this.CallRecording = CallRecording;
  }

  public ServiceVOIPAccountEditData DoNotDisturb(@.annotation.Nullable ServiceVOIPSharedDoNotDisturb DoNotDisturb) {
    
    this.DoNotDisturb = DoNotDisturb;
    return this;
  }

  /**
   * Get DoNotDisturb
   * @return DoNotDisturb
   */
  @.annotation.Nullable

  public ServiceVOIPSharedDoNotDisturb GetDoNotDisturb() {
    return DoNotDisturb;
  }


  public void setDoNotDisturb(@.annotation.Nullable ServiceVOIPSharedDoNotDisturb DoNotDisturb) {
    this.DoNotDisturb = DoNotDisturb;
  }

  public ServiceVOIPAccountEditData Enabled(@.annotation.Nullable bool Enabled) {
    
    this.Enabled = Enabled;
    return this;
  }

  /**
   * Get Enabled
   * @return Enabled
   */
  @.annotation.Nullable

  public bool getEnabled() {
    return Enabled;
  }


  public void setEnabled(@.annotation.Nullable bool Enabled) {
    this.Enabled = Enabled;
  }

  public ServiceVOIPAccountEditData MusicOnHold(@.annotation.Nullable ServiceVOIPAccountMusicOnHold MusicOnHold) {
    
    this.MusicOnHold = MusicOnHold;
    return this;
  }

  /**
   * Get MusicOnHold
   * @return MusicOnHold
   */
  @.annotation.Nullable

  public ServiceVOIPAccountMusicOnHold GetMusicOnHold() {
    return MusicOnHold;
  }


  public void setMusicOnHold(@.annotation.Nullable ServiceVOIPAccountMusicOnHold MusicOnHold) {
    this.MusicOnHold = MusicOnHold;
  }

  public ServiceVOIPAccountEditData Name(@.annotation.Nonnull string Name) {
    
    this.Name = Name;
    return this;
  }

  /**
   * Get Name
   * @return Name
   */
  @.annotation.Nonnull

  public string GetName() {
    return Name;
  }


  public void setName(@.annotation.Nonnull string Name) {
    this.Name = Name;
  }

  public ServiceVOIPAccountEditData Timezone(@.annotation.Nonnull string Timezone) {
    
    this.Timezone = Timezone;
    return this;
  }

  /**
   * Get Timezone
   * @return Timezone
   */
  @.annotation.Nonnull

  public string GetTimezone() {
    return Timezone;
  }


  public void setTimezone(@.annotation.Nonnull string Timezone) {
    this.Timezone = Timezone;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPAccountEditData ServiceVOIPAccountEditData = (ServiceVOIPAccountEditData) o;
    return Objects.equals(this.CallRecording, ServiceVOIPAccountEditData.CallRecording) &&
        Objects.equals(this.DoNotDisturb, ServiceVOIPAccountEditData.DoNotDisturb) &&
        Objects.equals(this.Enabled, ServiceVOIPAccountEditData.Enabled) &&
        Objects.equals(this.MusicOnHold, ServiceVOIPAccountEditData.MusicOnHold) &&
        Objects.equals(this.Name, ServiceVOIPAccountEditData.Name) &&
        Objects.equals(this.Timezone, ServiceVOIPAccountEditData.Timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CallRecording, DoNotDisturb, Enabled, MusicOnHold, Name, Timezone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPAccountEditData {\n");
    sb.append("    CallRecording: ").append(toIndentedString(CallRecording)).append("\n");
    sb.append("    DoNotDisturb: ").append(toIndentedString(DoNotDisturb)).append("\n");
    sb.append("    Enabled: ").append(toIndentedString(Enabled)).append("\n");
    sb.append("    MusicOnHold: ").append(toIndentedString(MusicOnHold)).append("\n");
    sb.append("    Name: ").append(toIndentedString(Name)).append("\n");
    sb.append("    Timezone: ").append(toIndentedString(Timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

