/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapi;

import java.util.Objects;
import java.util.Arrays;
import bytes;
import fmt;

/**
 * ServiceVOIPCallQueueEnableMembershipData
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.GoClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceVOIPCallQueueEnableMembershipData {
  @.annotation.Nonnull
  private bool AcceptCharges;

  public ServiceVOIPCallQueueEnableMembershipData() {
  }

  public ServiceVOIPCallQueueEnableMembershipData AcceptCharges(@.annotation.Nonnull bool AcceptCharges) {
    
    this.AcceptCharges = AcceptCharges;
    return this;
  }

  /**
   * Get AcceptCharges
   * @return AcceptCharges
   */
  @.annotation.Nonnull

  public bool getAcceptCharges() {
    return AcceptCharges;
  }


  public void setAcceptCharges(@.annotation.Nonnull bool AcceptCharges) {
    this.AcceptCharges = AcceptCharges;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPCallQueueEnableMembershipData ServiceVOIPCallQueueEnableMembershipData = (ServiceVOIPCallQueueEnableMembershipData) o;
    return Objects.equals(this.AcceptCharges, ServiceVOIPCallQueueEnableMembershipData.AcceptCharges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(AcceptCharges);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPCallQueueEnableMembershipData {\n");
    sb.append("    AcceptCharges: ").append(toIndentedString(AcceptCharges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

