/*
White Label Communications CPaas API Documentation

A CPaaS platform API

API version: 1.1
Contact: support@whitelabelcomm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServiceCdrOutputShort type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceCdrOutputShort{}

// ServiceCdrOutputShort struct for ServiceCdrOutputShort
type ServiceCdrOutputShort struct {
	AuthorizingId *string `json:"authorizing_id,omitempty"`
	BillingSeconds *int32 `json:"billing_seconds,omitempty"`
	BridgeId *string `json:"bridge_id,omitempty"`
	CallId *string `json:"call_id,omitempty"`
	CallPriority *string `json:"call_priority,omitempty"`
	CallType *string `json:"call_type,omitempty"`
	CalleeIdName *string `json:"callee_id_name,omitempty"`
	CalleeIdNumber *string `json:"callee_id_number,omitempty"`
	CallerIdName *string `json:"caller_id_name,omitempty"`
	CallerIdNumber *string `json:"caller_id_number,omitempty"`
	CallingFrom *string `json:"calling_from,omitempty"`
	Cost *string `json:"cost,omitempty"`
	DialedNumber *string `json:"dialed_number,omitempty"`
	Direction *string `json:"direction,omitempty"`
	DurationSeconds *int32 `json:"duration_seconds,omitempty"`
	From *string `json:"from,omitempty"`
	HangupCause *string `json:"hangup_cause,omitempty"`
	Id *string `json:"id,omitempty"`
	InteractionId *string `json:"interaction_id,omitempty"`
	MediaRecordings []map[string]interface{} `json:"media_recordings,omitempty"`
	MediaServer *string `json:"media_server,omitempty"`
	OtherLegCallId *string `json:"other_leg_call_id,omitempty"`
	OwnerId *string `json:"owner_id,omitempty"`
	Rate *string `json:"rate,omitempty"`
	RateName *string `json:"rate_name,omitempty"`
	RecordingUrl *string `json:"recording_url,omitempty"`
	Request *string `json:"request,omitempty"`
	Timestamp *int32 `json:"timestamp,omitempty"`
	TimestampDatetime *string `json:"timestamp_datetime,omitempty"`
	To *string `json:"to,omitempty"`
}

// NewServiceCdrOutputShort instantiates a new ServiceCdrOutputShort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceCdrOutputShort() *ServiceCdrOutputShort {
	this := ServiceCdrOutputShort{}
	return &this
}

// NewServiceCdrOutputShortWithDefaults instantiates a new ServiceCdrOutputShort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceCdrOutputShortWithDefaults() *ServiceCdrOutputShort {
	this := ServiceCdrOutputShort{}
	return &this
}

// GetAuthorizingId returns the AuthorizingId field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetAuthorizingId() string {
	if o == nil || IsNil(o.AuthorizingId) {
		var ret string
		return ret
	}
	return *o.AuthorizingId
}

// GetAuthorizingIdOk returns a tuple with the AuthorizingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetAuthorizingIdOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorizingId) {
		return nil, false
	}
	return o.AuthorizingId, true
}

// HasAuthorizingId returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasAuthorizingId() bool {
	if o != nil && !IsNil(o.AuthorizingId) {
		return true
	}

	return false
}

// SetAuthorizingId gets a reference to the given string and assigns it to the AuthorizingId field.
func (o *ServiceCdrOutputShort) SetAuthorizingId(v string) {
	o.AuthorizingId = &v
}

// GetBillingSeconds returns the BillingSeconds field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetBillingSeconds() int32 {
	if o == nil || IsNil(o.BillingSeconds) {
		var ret int32
		return ret
	}
	return *o.BillingSeconds
}

// GetBillingSecondsOk returns a tuple with the BillingSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetBillingSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.BillingSeconds) {
		return nil, false
	}
	return o.BillingSeconds, true
}

// HasBillingSeconds returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasBillingSeconds() bool {
	if o != nil && !IsNil(o.BillingSeconds) {
		return true
	}

	return false
}

// SetBillingSeconds gets a reference to the given int32 and assigns it to the BillingSeconds field.
func (o *ServiceCdrOutputShort) SetBillingSeconds(v int32) {
	o.BillingSeconds = &v
}

// GetBridgeId returns the BridgeId field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetBridgeId() string {
	if o == nil || IsNil(o.BridgeId) {
		var ret string
		return ret
	}
	return *o.BridgeId
}

// GetBridgeIdOk returns a tuple with the BridgeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetBridgeIdOk() (*string, bool) {
	if o == nil || IsNil(o.BridgeId) {
		return nil, false
	}
	return o.BridgeId, true
}

// HasBridgeId returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasBridgeId() bool {
	if o != nil && !IsNil(o.BridgeId) {
		return true
	}

	return false
}

// SetBridgeId gets a reference to the given string and assigns it to the BridgeId field.
func (o *ServiceCdrOutputShort) SetBridgeId(v string) {
	o.BridgeId = &v
}

// GetCallId returns the CallId field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetCallId() string {
	if o == nil || IsNil(o.CallId) {
		var ret string
		return ret
	}
	return *o.CallId
}

// GetCallIdOk returns a tuple with the CallId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetCallIdOk() (*string, bool) {
	if o == nil || IsNil(o.CallId) {
		return nil, false
	}
	return o.CallId, true
}

// HasCallId returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasCallId() bool {
	if o != nil && !IsNil(o.CallId) {
		return true
	}

	return false
}

// SetCallId gets a reference to the given string and assigns it to the CallId field.
func (o *ServiceCdrOutputShort) SetCallId(v string) {
	o.CallId = &v
}

// GetCallPriority returns the CallPriority field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetCallPriority() string {
	if o == nil || IsNil(o.CallPriority) {
		var ret string
		return ret
	}
	return *o.CallPriority
}

// GetCallPriorityOk returns a tuple with the CallPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetCallPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.CallPriority) {
		return nil, false
	}
	return o.CallPriority, true
}

// HasCallPriority returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasCallPriority() bool {
	if o != nil && !IsNil(o.CallPriority) {
		return true
	}

	return false
}

// SetCallPriority gets a reference to the given string and assigns it to the CallPriority field.
func (o *ServiceCdrOutputShort) SetCallPriority(v string) {
	o.CallPriority = &v
}

// GetCallType returns the CallType field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetCallType() string {
	if o == nil || IsNil(o.CallType) {
		var ret string
		return ret
	}
	return *o.CallType
}

// GetCallTypeOk returns a tuple with the CallType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetCallTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CallType) {
		return nil, false
	}
	return o.CallType, true
}

// HasCallType returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasCallType() bool {
	if o != nil && !IsNil(o.CallType) {
		return true
	}

	return false
}

// SetCallType gets a reference to the given string and assigns it to the CallType field.
func (o *ServiceCdrOutputShort) SetCallType(v string) {
	o.CallType = &v
}

// GetCalleeIdName returns the CalleeIdName field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetCalleeIdName() string {
	if o == nil || IsNil(o.CalleeIdName) {
		var ret string
		return ret
	}
	return *o.CalleeIdName
}

// GetCalleeIdNameOk returns a tuple with the CalleeIdName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetCalleeIdNameOk() (*string, bool) {
	if o == nil || IsNil(o.CalleeIdName) {
		return nil, false
	}
	return o.CalleeIdName, true
}

// HasCalleeIdName returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasCalleeIdName() bool {
	if o != nil && !IsNil(o.CalleeIdName) {
		return true
	}

	return false
}

// SetCalleeIdName gets a reference to the given string and assigns it to the CalleeIdName field.
func (o *ServiceCdrOutputShort) SetCalleeIdName(v string) {
	o.CalleeIdName = &v
}

// GetCalleeIdNumber returns the CalleeIdNumber field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetCalleeIdNumber() string {
	if o == nil || IsNil(o.CalleeIdNumber) {
		var ret string
		return ret
	}
	return *o.CalleeIdNumber
}

// GetCalleeIdNumberOk returns a tuple with the CalleeIdNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetCalleeIdNumberOk() (*string, bool) {
	if o == nil || IsNil(o.CalleeIdNumber) {
		return nil, false
	}
	return o.CalleeIdNumber, true
}

// HasCalleeIdNumber returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasCalleeIdNumber() bool {
	if o != nil && !IsNil(o.CalleeIdNumber) {
		return true
	}

	return false
}

// SetCalleeIdNumber gets a reference to the given string and assigns it to the CalleeIdNumber field.
func (o *ServiceCdrOutputShort) SetCalleeIdNumber(v string) {
	o.CalleeIdNumber = &v
}

// GetCallerIdName returns the CallerIdName field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetCallerIdName() string {
	if o == nil || IsNil(o.CallerIdName) {
		var ret string
		return ret
	}
	return *o.CallerIdName
}

// GetCallerIdNameOk returns a tuple with the CallerIdName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetCallerIdNameOk() (*string, bool) {
	if o == nil || IsNil(o.CallerIdName) {
		return nil, false
	}
	return o.CallerIdName, true
}

// HasCallerIdName returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasCallerIdName() bool {
	if o != nil && !IsNil(o.CallerIdName) {
		return true
	}

	return false
}

// SetCallerIdName gets a reference to the given string and assigns it to the CallerIdName field.
func (o *ServiceCdrOutputShort) SetCallerIdName(v string) {
	o.CallerIdName = &v
}

// GetCallerIdNumber returns the CallerIdNumber field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetCallerIdNumber() string {
	if o == nil || IsNil(o.CallerIdNumber) {
		var ret string
		return ret
	}
	return *o.CallerIdNumber
}

// GetCallerIdNumberOk returns a tuple with the CallerIdNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetCallerIdNumberOk() (*string, bool) {
	if o == nil || IsNil(o.CallerIdNumber) {
		return nil, false
	}
	return o.CallerIdNumber, true
}

// HasCallerIdNumber returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasCallerIdNumber() bool {
	if o != nil && !IsNil(o.CallerIdNumber) {
		return true
	}

	return false
}

// SetCallerIdNumber gets a reference to the given string and assigns it to the CallerIdNumber field.
func (o *ServiceCdrOutputShort) SetCallerIdNumber(v string) {
	o.CallerIdNumber = &v
}

// GetCallingFrom returns the CallingFrom field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetCallingFrom() string {
	if o == nil || IsNil(o.CallingFrom) {
		var ret string
		return ret
	}
	return *o.CallingFrom
}

// GetCallingFromOk returns a tuple with the CallingFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetCallingFromOk() (*string, bool) {
	if o == nil || IsNil(o.CallingFrom) {
		return nil, false
	}
	return o.CallingFrom, true
}

// HasCallingFrom returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasCallingFrom() bool {
	if o != nil && !IsNil(o.CallingFrom) {
		return true
	}

	return false
}

// SetCallingFrom gets a reference to the given string and assigns it to the CallingFrom field.
func (o *ServiceCdrOutputShort) SetCallingFrom(v string) {
	o.CallingFrom = &v
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetCost() string {
	if o == nil || IsNil(o.Cost) {
		var ret string
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetCostOk() (*string, bool) {
	if o == nil || IsNil(o.Cost) {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasCost() bool {
	if o != nil && !IsNil(o.Cost) {
		return true
	}

	return false
}

// SetCost gets a reference to the given string and assigns it to the Cost field.
func (o *ServiceCdrOutputShort) SetCost(v string) {
	o.Cost = &v
}

// GetDialedNumber returns the DialedNumber field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetDialedNumber() string {
	if o == nil || IsNil(o.DialedNumber) {
		var ret string
		return ret
	}
	return *o.DialedNumber
}

// GetDialedNumberOk returns a tuple with the DialedNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetDialedNumberOk() (*string, bool) {
	if o == nil || IsNil(o.DialedNumber) {
		return nil, false
	}
	return o.DialedNumber, true
}

// HasDialedNumber returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasDialedNumber() bool {
	if o != nil && !IsNil(o.DialedNumber) {
		return true
	}

	return false
}

// SetDialedNumber gets a reference to the given string and assigns it to the DialedNumber field.
func (o *ServiceCdrOutputShort) SetDialedNumber(v string) {
	o.DialedNumber = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetDirection() string {
	if o == nil || IsNil(o.Direction) {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *ServiceCdrOutputShort) SetDirection(v string) {
	o.Direction = &v
}

// GetDurationSeconds returns the DurationSeconds field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetDurationSeconds() int32 {
	if o == nil || IsNil(o.DurationSeconds) {
		var ret int32
		return ret
	}
	return *o.DurationSeconds
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetDurationSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.DurationSeconds) {
		return nil, false
	}
	return o.DurationSeconds, true
}

// HasDurationSeconds returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasDurationSeconds() bool {
	if o != nil && !IsNil(o.DurationSeconds) {
		return true
	}

	return false
}

// SetDurationSeconds gets a reference to the given int32 and assigns it to the DurationSeconds field.
func (o *ServiceCdrOutputShort) SetDurationSeconds(v int32) {
	o.DurationSeconds = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *ServiceCdrOutputShort) SetFrom(v string) {
	o.From = &v
}

// GetHangupCause returns the HangupCause field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetHangupCause() string {
	if o == nil || IsNil(o.HangupCause) {
		var ret string
		return ret
	}
	return *o.HangupCause
}

// GetHangupCauseOk returns a tuple with the HangupCause field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetHangupCauseOk() (*string, bool) {
	if o == nil || IsNil(o.HangupCause) {
		return nil, false
	}
	return o.HangupCause, true
}

// HasHangupCause returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasHangupCause() bool {
	if o != nil && !IsNil(o.HangupCause) {
		return true
	}

	return false
}

// SetHangupCause gets a reference to the given string and assigns it to the HangupCause field.
func (o *ServiceCdrOutputShort) SetHangupCause(v string) {
	o.HangupCause = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ServiceCdrOutputShort) SetId(v string) {
	o.Id = &v
}

// GetInteractionId returns the InteractionId field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetInteractionId() string {
	if o == nil || IsNil(o.InteractionId) {
		var ret string
		return ret
	}
	return *o.InteractionId
}

// GetInteractionIdOk returns a tuple with the InteractionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetInteractionIdOk() (*string, bool) {
	if o == nil || IsNil(o.InteractionId) {
		return nil, false
	}
	return o.InteractionId, true
}

// HasInteractionId returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasInteractionId() bool {
	if o != nil && !IsNil(o.InteractionId) {
		return true
	}

	return false
}

// SetInteractionId gets a reference to the given string and assigns it to the InteractionId field.
func (o *ServiceCdrOutputShort) SetInteractionId(v string) {
	o.InteractionId = &v
}

// GetMediaRecordings returns the MediaRecordings field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetMediaRecordings() []map[string]interface{} {
	if o == nil || IsNil(o.MediaRecordings) {
		var ret []map[string]interface{}
		return ret
	}
	return o.MediaRecordings
}

// GetMediaRecordingsOk returns a tuple with the MediaRecordings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetMediaRecordingsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.MediaRecordings) {
		return nil, false
	}
	return o.MediaRecordings, true
}

// HasMediaRecordings returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasMediaRecordings() bool {
	if o != nil && !IsNil(o.MediaRecordings) {
		return true
	}

	return false
}

// SetMediaRecordings gets a reference to the given []map[string]interface{} and assigns it to the MediaRecordings field.
func (o *ServiceCdrOutputShort) SetMediaRecordings(v []map[string]interface{}) {
	o.MediaRecordings = v
}

// GetMediaServer returns the MediaServer field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetMediaServer() string {
	if o == nil || IsNil(o.MediaServer) {
		var ret string
		return ret
	}
	return *o.MediaServer
}

// GetMediaServerOk returns a tuple with the MediaServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetMediaServerOk() (*string, bool) {
	if o == nil || IsNil(o.MediaServer) {
		return nil, false
	}
	return o.MediaServer, true
}

// HasMediaServer returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasMediaServer() bool {
	if o != nil && !IsNil(o.MediaServer) {
		return true
	}

	return false
}

// SetMediaServer gets a reference to the given string and assigns it to the MediaServer field.
func (o *ServiceCdrOutputShort) SetMediaServer(v string) {
	o.MediaServer = &v
}

// GetOtherLegCallId returns the OtherLegCallId field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetOtherLegCallId() string {
	if o == nil || IsNil(o.OtherLegCallId) {
		var ret string
		return ret
	}
	return *o.OtherLegCallId
}

// GetOtherLegCallIdOk returns a tuple with the OtherLegCallId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetOtherLegCallIdOk() (*string, bool) {
	if o == nil || IsNil(o.OtherLegCallId) {
		return nil, false
	}
	return o.OtherLegCallId, true
}

// HasOtherLegCallId returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasOtherLegCallId() bool {
	if o != nil && !IsNil(o.OtherLegCallId) {
		return true
	}

	return false
}

// SetOtherLegCallId gets a reference to the given string and assigns it to the OtherLegCallId field.
func (o *ServiceCdrOutputShort) SetOtherLegCallId(v string) {
	o.OtherLegCallId = &v
}

// GetOwnerId returns the OwnerId field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetOwnerId() string {
	if o == nil || IsNil(o.OwnerId) {
		var ret string
		return ret
	}
	return *o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetOwnerIdOk() (*string, bool) {
	if o == nil || IsNil(o.OwnerId) {
		return nil, false
	}
	return o.OwnerId, true
}

// HasOwnerId returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasOwnerId() bool {
	if o != nil && !IsNil(o.OwnerId) {
		return true
	}

	return false
}

// SetOwnerId gets a reference to the given string and assigns it to the OwnerId field.
func (o *ServiceCdrOutputShort) SetOwnerId(v string) {
	o.OwnerId = &v
}

// GetRate returns the Rate field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetRate() string {
	if o == nil || IsNil(o.Rate) {
		var ret string
		return ret
	}
	return *o.Rate
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetRateOk() (*string, bool) {
	if o == nil || IsNil(o.Rate) {
		return nil, false
	}
	return o.Rate, true
}

// HasRate returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasRate() bool {
	if o != nil && !IsNil(o.Rate) {
		return true
	}

	return false
}

// SetRate gets a reference to the given string and assigns it to the Rate field.
func (o *ServiceCdrOutputShort) SetRate(v string) {
	o.Rate = &v
}

// GetRateName returns the RateName field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetRateName() string {
	if o == nil || IsNil(o.RateName) {
		var ret string
		return ret
	}
	return *o.RateName
}

// GetRateNameOk returns a tuple with the RateName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetRateNameOk() (*string, bool) {
	if o == nil || IsNil(o.RateName) {
		return nil, false
	}
	return o.RateName, true
}

// HasRateName returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasRateName() bool {
	if o != nil && !IsNil(o.RateName) {
		return true
	}

	return false
}

// SetRateName gets a reference to the given string and assigns it to the RateName field.
func (o *ServiceCdrOutputShort) SetRateName(v string) {
	o.RateName = &v
}

// GetRecordingUrl returns the RecordingUrl field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetRecordingUrl() string {
	if o == nil || IsNil(o.RecordingUrl) {
		var ret string
		return ret
	}
	return *o.RecordingUrl
}

// GetRecordingUrlOk returns a tuple with the RecordingUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetRecordingUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RecordingUrl) {
		return nil, false
	}
	return o.RecordingUrl, true
}

// HasRecordingUrl returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasRecordingUrl() bool {
	if o != nil && !IsNil(o.RecordingUrl) {
		return true
	}

	return false
}

// SetRecordingUrl gets a reference to the given string and assigns it to the RecordingUrl field.
func (o *ServiceCdrOutputShort) SetRecordingUrl(v string) {
	o.RecordingUrl = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetRequest() string {
	if o == nil || IsNil(o.Request) {
		var ret string
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetRequestOk() (*string, bool) {
	if o == nil || IsNil(o.Request) {
		return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasRequest() bool {
	if o != nil && !IsNil(o.Request) {
		return true
	}

	return false
}

// SetRequest gets a reference to the given string and assigns it to the Request field.
func (o *ServiceCdrOutputShort) SetRequest(v string) {
	o.Request = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int32 and assigns it to the Timestamp field.
func (o *ServiceCdrOutputShort) SetTimestamp(v int32) {
	o.Timestamp = &v
}

// GetTimestampDatetime returns the TimestampDatetime field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetTimestampDatetime() string {
	if o == nil || IsNil(o.TimestampDatetime) {
		var ret string
		return ret
	}
	return *o.TimestampDatetime
}

// GetTimestampDatetimeOk returns a tuple with the TimestampDatetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetTimestampDatetimeOk() (*string, bool) {
	if o == nil || IsNil(o.TimestampDatetime) {
		return nil, false
	}
	return o.TimestampDatetime, true
}

// HasTimestampDatetime returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasTimestampDatetime() bool {
	if o != nil && !IsNil(o.TimestampDatetime) {
		return true
	}

	return false
}

// SetTimestampDatetime gets a reference to the given string and assigns it to the TimestampDatetime field.
func (o *ServiceCdrOutputShort) SetTimestampDatetime(v string) {
	o.TimestampDatetime = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *ServiceCdrOutputShort) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCdrOutputShort) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *ServiceCdrOutputShort) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *ServiceCdrOutputShort) SetTo(v string) {
	o.To = &v
}

func (o ServiceCdrOutputShort) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceCdrOutputShort) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthorizingId) {
		toSerialize["authorizing_id"] = o.AuthorizingId
	}
	if !IsNil(o.BillingSeconds) {
		toSerialize["billing_seconds"] = o.BillingSeconds
	}
	if !IsNil(o.BridgeId) {
		toSerialize["bridge_id"] = o.BridgeId
	}
	if !IsNil(o.CallId) {
		toSerialize["call_id"] = o.CallId
	}
	if !IsNil(o.CallPriority) {
		toSerialize["call_priority"] = o.CallPriority
	}
	if !IsNil(o.CallType) {
		toSerialize["call_type"] = o.CallType
	}
	if !IsNil(o.CalleeIdName) {
		toSerialize["callee_id_name"] = o.CalleeIdName
	}
	if !IsNil(o.CalleeIdNumber) {
		toSerialize["callee_id_number"] = o.CalleeIdNumber
	}
	if !IsNil(o.CallerIdName) {
		toSerialize["caller_id_name"] = o.CallerIdName
	}
	if !IsNil(o.CallerIdNumber) {
		toSerialize["caller_id_number"] = o.CallerIdNumber
	}
	if !IsNil(o.CallingFrom) {
		toSerialize["calling_from"] = o.CallingFrom
	}
	if !IsNil(o.Cost) {
		toSerialize["cost"] = o.Cost
	}
	if !IsNil(o.DialedNumber) {
		toSerialize["dialed_number"] = o.DialedNumber
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.DurationSeconds) {
		toSerialize["duration_seconds"] = o.DurationSeconds
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.HangupCause) {
		toSerialize["hangup_cause"] = o.HangupCause
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InteractionId) {
		toSerialize["interaction_id"] = o.InteractionId
	}
	if !IsNil(o.MediaRecordings) {
		toSerialize["media_recordings"] = o.MediaRecordings
	}
	if !IsNil(o.MediaServer) {
		toSerialize["media_server"] = o.MediaServer
	}
	if !IsNil(o.OtherLegCallId) {
		toSerialize["other_leg_call_id"] = o.OtherLegCallId
	}
	if !IsNil(o.OwnerId) {
		toSerialize["owner_id"] = o.OwnerId
	}
	if !IsNil(o.Rate) {
		toSerialize["rate"] = o.Rate
	}
	if !IsNil(o.RateName) {
		toSerialize["rate_name"] = o.RateName
	}
	if !IsNil(o.RecordingUrl) {
		toSerialize["recording_url"] = o.RecordingUrl
	}
	if !IsNil(o.Request) {
		toSerialize["request"] = o.Request
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.TimestampDatetime) {
		toSerialize["timestamp_datetime"] = o.TimestampDatetime
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableServiceCdrOutputShort struct {
	value *ServiceCdrOutputShort
	isSet bool
}

func (v NullableServiceCdrOutputShort) Get() *ServiceCdrOutputShort {
	return v.value
}

func (v *NullableServiceCdrOutputShort) Set(val *ServiceCdrOutputShort) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceCdrOutputShort) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceCdrOutputShort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceCdrOutputShort(val *ServiceCdrOutputShort) *NullableServiceCdrOutputShort {
	return &NullableServiceCdrOutputShort{value: val, isSet: true}
}

func (v NullableServiceCdrOutputShort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceCdrOutputShort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


