/*
White Label Communications CPaas API Documentation

A CPaaS platform API

API version: 1.1
Contact: support@whitelabelcomm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServiceUserOutputFullCalleridExternal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceUserOutputFullCalleridExternal{}

// ServiceUserOutputFullCalleridExternal struct for ServiceUserOutputFullCalleridExternal
type ServiceUserOutputFullCalleridExternal struct {
	Number *string `json:"number,omitempty"`
}

// NewServiceUserOutputFullCalleridExternal instantiates a new ServiceUserOutputFullCalleridExternal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceUserOutputFullCalleridExternal() *ServiceUserOutputFullCalleridExternal {
	this := ServiceUserOutputFullCalleridExternal{}
	return &this
}

// NewServiceUserOutputFullCalleridExternalWithDefaults instantiates a new ServiceUserOutputFullCalleridExternal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceUserOutputFullCalleridExternalWithDefaults() *ServiceUserOutputFullCalleridExternal {
	this := ServiceUserOutputFullCalleridExternal{}
	return &this
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *ServiceUserOutputFullCalleridExternal) GetNumber() string {
	if o == nil || IsNil(o.Number) {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceUserOutputFullCalleridExternal) GetNumberOk() (*string, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *ServiceUserOutputFullCalleridExternal) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *ServiceUserOutputFullCalleridExternal) SetNumber(v string) {
	o.Number = &v
}

func (o ServiceUserOutputFullCalleridExternal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceUserOutputFullCalleridExternal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	return toSerialize, nil
}

type NullableServiceUserOutputFullCalleridExternal struct {
	value *ServiceUserOutputFullCalleridExternal
	isSet bool
}

func (v NullableServiceUserOutputFullCalleridExternal) Get() *ServiceUserOutputFullCalleridExternal {
	return v.value
}

func (v *NullableServiceUserOutputFullCalleridExternal) Set(val *ServiceUserOutputFullCalleridExternal) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceUserOutputFullCalleridExternal) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceUserOutputFullCalleridExternal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceUserOutputFullCalleridExternal(val *ServiceUserOutputFullCalleridExternal) *NullableServiceUserOutputFullCalleridExternal {
	return &NullableServiceUserOutputFullCalleridExternal{value: val, isSet: true}
}

func (v NullableServiceUserOutputFullCalleridExternal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceUserOutputFullCalleridExternal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


