/*
White Label Communications CPaas API Documentation

A CPaaS platform API

API version: 1.1
Contact: support@whitelabelcomm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServicePhoneNumberSearchOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicePhoneNumberSearchOutput{}

// ServicePhoneNumberSearchOutput struct for ServicePhoneNumberSearchOutput
type ServicePhoneNumberSearchOutput struct {
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

// NewServicePhoneNumberSearchOutput instantiates a new ServicePhoneNumberSearchOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicePhoneNumberSearchOutput() *ServicePhoneNumberSearchOutput {
	this := ServicePhoneNumberSearchOutput{}
	return &this
}

// NewServicePhoneNumberSearchOutputWithDefaults instantiates a new ServicePhoneNumberSearchOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicePhoneNumberSearchOutputWithDefaults() *ServicePhoneNumberSearchOutput {
	this := ServicePhoneNumberSearchOutput{}
	return &this
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *ServicePhoneNumberSearchOutput) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicePhoneNumberSearchOutput) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *ServicePhoneNumberSearchOutput) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *ServicePhoneNumberSearchOutput) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

func (o ServicePhoneNumberSearchOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicePhoneNumberSearchOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	return toSerialize, nil
}

type NullableServicePhoneNumberSearchOutput struct {
	value *ServicePhoneNumberSearchOutput
	isSet bool
}

func (v NullableServicePhoneNumberSearchOutput) Get() *ServicePhoneNumberSearchOutput {
	return v.value
}

func (v *NullableServicePhoneNumberSearchOutput) Set(val *ServicePhoneNumberSearchOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableServicePhoneNumberSearchOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableServicePhoneNumberSearchOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicePhoneNumberSearchOutput(val *ServicePhoneNumberSearchOutput) *NullableServicePhoneNumberSearchOutput {
	return &NullableServicePhoneNumberSearchOutput{value: val, isSet: true}
}

func (v NullableServicePhoneNumberSearchOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicePhoneNumberSearchOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


