/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapi;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceE911ActiveLocationOutput
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.GoClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceE911ActiveLocationOutput {
  @.annotation.Nullable
  private ServiceE911ActiveLocationStatus LocationStatus;

  public ServiceE911ActiveLocationOutput() {
  }

  public ServiceE911ActiveLocationOutput LocationStatus(@.annotation.Nullable ServiceE911ActiveLocationStatus LocationStatus) {
    
    this.LocationStatus = LocationStatus;
    return this;
  }

  /**
   * Get LocationStatus
   * @return LocationStatus
   */
  @.annotation.Nullable

  public ServiceE911ActiveLocationStatus GetLocationStatus() {
    return LocationStatus;
  }


  public void setLocationStatus(@.annotation.Nullable ServiceE911ActiveLocationStatus LocationStatus) {
    this.LocationStatus = LocationStatus;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceE911ActiveLocationOutput ServiceE911ActiveLocationOutput = (ServiceE911ActiveLocationOutput) o;
    return Objects.equals(this.LocationStatus, ServiceE911ActiveLocationOutput.LocationStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(LocationStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceE911ActiveLocationOutput {\n");
    sb.append("    LocationStatus: ").append(toIndentedString(LocationStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

