/*
White Label Communications CPaas API Documentation

A CPaaS platform API

API version: 1.1
Contact: support@whitelabelcomm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceVOIPVoicemailMessageAddData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceVOIPVoicemailMessageAddData{}

// ServiceVOIPVoicemailMessageAddData struct for ServiceVOIPVoicemailMessageAddData
type ServiceVOIPVoicemailMessageAddData struct {
	CallerIdName *string `json:"caller_id_name,omitempty"`
	CallerIdNumber *string `json:"caller_id_number,omitempty"`
	Folder string `json:"folder"`
	From *string `json:"from,omitempty"`
	To *string `json:"to,omitempty"`
}

type _ServiceVOIPVoicemailMessageAddData ServiceVOIPVoicemailMessageAddData

// NewServiceVOIPVoicemailMessageAddData instantiates a new ServiceVOIPVoicemailMessageAddData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceVOIPVoicemailMessageAddData(folder string) *ServiceVOIPVoicemailMessageAddData {
	this := ServiceVOIPVoicemailMessageAddData{}
	this.Folder = folder
	return &this
}

// NewServiceVOIPVoicemailMessageAddDataWithDefaults instantiates a new ServiceVOIPVoicemailMessageAddData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceVOIPVoicemailMessageAddDataWithDefaults() *ServiceVOIPVoicemailMessageAddData {
	this := ServiceVOIPVoicemailMessageAddData{}
	return &this
}

// GetCallerIdName returns the CallerIdName field value if set, zero value otherwise.
func (o *ServiceVOIPVoicemailMessageAddData) GetCallerIdName() string {
	if o == nil || IsNil(o.CallerIdName) {
		var ret string
		return ret
	}
	return *o.CallerIdName
}

// GetCallerIdNameOk returns a tuple with the CallerIdName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceVOIPVoicemailMessageAddData) GetCallerIdNameOk() (*string, bool) {
	if o == nil || IsNil(o.CallerIdName) {
		return nil, false
	}
	return o.CallerIdName, true
}

// HasCallerIdName returns a boolean if a field has been set.
func (o *ServiceVOIPVoicemailMessageAddData) HasCallerIdName() bool {
	if o != nil && !IsNil(o.CallerIdName) {
		return true
	}

	return false
}

// SetCallerIdName gets a reference to the given string and assigns it to the CallerIdName field.
func (o *ServiceVOIPVoicemailMessageAddData) SetCallerIdName(v string) {
	o.CallerIdName = &v
}

// GetCallerIdNumber returns the CallerIdNumber field value if set, zero value otherwise.
func (o *ServiceVOIPVoicemailMessageAddData) GetCallerIdNumber() string {
	if o == nil || IsNil(o.CallerIdNumber) {
		var ret string
		return ret
	}
	return *o.CallerIdNumber
}

// GetCallerIdNumberOk returns a tuple with the CallerIdNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceVOIPVoicemailMessageAddData) GetCallerIdNumberOk() (*string, bool) {
	if o == nil || IsNil(o.CallerIdNumber) {
		return nil, false
	}
	return o.CallerIdNumber, true
}

// HasCallerIdNumber returns a boolean if a field has been set.
func (o *ServiceVOIPVoicemailMessageAddData) HasCallerIdNumber() bool {
	if o != nil && !IsNil(o.CallerIdNumber) {
		return true
	}

	return false
}

// SetCallerIdNumber gets a reference to the given string and assigns it to the CallerIdNumber field.
func (o *ServiceVOIPVoicemailMessageAddData) SetCallerIdNumber(v string) {
	o.CallerIdNumber = &v
}

// GetFolder returns the Folder field value
func (o *ServiceVOIPVoicemailMessageAddData) GetFolder() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Folder
}

// GetFolderOk returns a tuple with the Folder field value
// and a boolean to check if the value has been set.
func (o *ServiceVOIPVoicemailMessageAddData) GetFolderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Folder, true
}

// SetFolder sets field value
func (o *ServiceVOIPVoicemailMessageAddData) SetFolder(v string) {
	o.Folder = v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *ServiceVOIPVoicemailMessageAddData) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceVOIPVoicemailMessageAddData) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *ServiceVOIPVoicemailMessageAddData) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *ServiceVOIPVoicemailMessageAddData) SetFrom(v string) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *ServiceVOIPVoicemailMessageAddData) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceVOIPVoicemailMessageAddData) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *ServiceVOIPVoicemailMessageAddData) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *ServiceVOIPVoicemailMessageAddData) SetTo(v string) {
	o.To = &v
}

func (o ServiceVOIPVoicemailMessageAddData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceVOIPVoicemailMessageAddData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CallerIdName) {
		toSerialize["caller_id_name"] = o.CallerIdName
	}
	if !IsNil(o.CallerIdNumber) {
		toSerialize["caller_id_number"] = o.CallerIdNumber
	}
	toSerialize["folder"] = o.Folder
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

func (o *ServiceVOIPVoicemailMessageAddData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"folder",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceVOIPVoicemailMessageAddData := _ServiceVOIPVoicemailMessageAddData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceVOIPVoicemailMessageAddData)

	if err != nil {
		return err
	}

	*o = ServiceVOIPVoicemailMessageAddData(varServiceVOIPVoicemailMessageAddData)

	return err
}

type NullableServiceVOIPVoicemailMessageAddData struct {
	value *ServiceVOIPVoicemailMessageAddData
	isSet bool
}

func (v NullableServiceVOIPVoicemailMessageAddData) Get() *ServiceVOIPVoicemailMessageAddData {
	return v.value
}

func (v *NullableServiceVOIPVoicemailMessageAddData) Set(val *ServiceVOIPVoicemailMessageAddData) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceVOIPVoicemailMessageAddData) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceVOIPVoicemailMessageAddData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceVOIPVoicemailMessageAddData(val *ServiceVOIPVoicemailMessageAddData) *NullableServiceVOIPVoicemailMessageAddData {
	return &NullableServiceVOIPVoicemailMessageAddData{value: val, isSet: true}
}

func (v NullableServiceVOIPVoicemailMessageAddData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceVOIPVoicemailMessageAddData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


