/*
White Label Communications CPaas API Documentation

A CPaaS platform API

API version: 1.1
Contact: support@whitelabelcomm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServiceVOIPDeviceAddEdit5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceVOIPDeviceAddEdit5{}

// ServiceVOIPDeviceAddEdit5 struct for ServiceVOIPDeviceAddEdit5
type ServiceVOIPDeviceAddEdit5 struct {
	Codecs []string `json:"codecs,omitempty"`
}

// NewServiceVOIPDeviceAddEdit5 instantiates a new ServiceVOIPDeviceAddEdit5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceVOIPDeviceAddEdit5() *ServiceVOIPDeviceAddEdit5 {
	this := ServiceVOIPDeviceAddEdit5{}
	return &this
}

// NewServiceVOIPDeviceAddEdit5WithDefaults instantiates a new ServiceVOIPDeviceAddEdit5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceVOIPDeviceAddEdit5WithDefaults() *ServiceVOIPDeviceAddEdit5 {
	this := ServiceVOIPDeviceAddEdit5{}
	return &this
}

// GetCodecs returns the Codecs field value if set, zero value otherwise.
func (o *ServiceVOIPDeviceAddEdit5) GetCodecs() []string {
	if o == nil || IsNil(o.Codecs) {
		var ret []string
		return ret
	}
	return o.Codecs
}

// GetCodecsOk returns a tuple with the Codecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceVOIPDeviceAddEdit5) GetCodecsOk() ([]string, bool) {
	if o == nil || IsNil(o.Codecs) {
		return nil, false
	}
	return o.Codecs, true
}

// HasCodecs returns a boolean if a field has been set.
func (o *ServiceVOIPDeviceAddEdit5) HasCodecs() bool {
	if o != nil && !IsNil(o.Codecs) {
		return true
	}

	return false
}

// SetCodecs gets a reference to the given []string and assigns it to the Codecs field.
func (o *ServiceVOIPDeviceAddEdit5) SetCodecs(v []string) {
	o.Codecs = v
}

func (o ServiceVOIPDeviceAddEdit5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceVOIPDeviceAddEdit5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Codecs) {
		toSerialize["codecs"] = o.Codecs
	}
	return toSerialize, nil
}

type NullableServiceVOIPDeviceAddEdit5 struct {
	value *ServiceVOIPDeviceAddEdit5
	isSet bool
}

func (v NullableServiceVOIPDeviceAddEdit5) Get() *ServiceVOIPDeviceAddEdit5 {
	return v.value
}

func (v *NullableServiceVOIPDeviceAddEdit5) Set(val *ServiceVOIPDeviceAddEdit5) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceVOIPDeviceAddEdit5) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceVOIPDeviceAddEdit5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceVOIPDeviceAddEdit5(val *ServiceVOIPDeviceAddEdit5) *NullableServiceVOIPDeviceAddEdit5 {
	return &NullableServiceVOIPDeviceAddEdit5{value: val, isSet: true}
}

func (v NullableServiceVOIPDeviceAddEdit5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceVOIPDeviceAddEdit5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


