/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapi;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceMenuOutputFullMedia
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.GoClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceMenuOutputFullMedia {
  @.annotation.Nullable
  private string Greeting;

  @.annotation.Nullable
  private map[string]interface{} InvalidMedia;

  @.annotation.Nullable
  private map[string]interface{} TransferMedia;

  public ServiceMenuOutputFullMedia() {
  }

  public ServiceMenuOutputFullMedia Greeting(@.annotation.Nullable string Greeting) {
    
    this.Greeting = Greeting;
    return this;
  }

  /**
   * Get Greeting
   * @return Greeting
   */
  @.annotation.Nullable

  public string GetGreeting() {
    return Greeting;
  }


  public void setGreeting(@.annotation.Nullable string Greeting) {
    this.Greeting = Greeting;
  }

  public ServiceMenuOutputFullMedia InvalidMedia(@.annotation.Nullable map[string]interface{} InvalidMedia) {
    
    this.InvalidMedia = InvalidMedia;
    return this;
  }

  /**
   * Get InvalidMedia
   * @return InvalidMedia
   */
  @.annotation.Nullable

  public map[string]interface{} GetInvalidMedia() {
    return InvalidMedia;
  }


  public void setInvalidMedia(@.annotation.Nullable map[string]interface{} InvalidMedia) {
    this.InvalidMedia = InvalidMedia;
  }

  public ServiceMenuOutputFullMedia TransferMedia(@.annotation.Nullable map[string]interface{} TransferMedia) {
    
    this.TransferMedia = TransferMedia;
    return this;
  }

  /**
   * Get TransferMedia
   * @return TransferMedia
   */
  @.annotation.Nullable

  public map[string]interface{} GetTransferMedia() {
    return TransferMedia;
  }


  public void setTransferMedia(@.annotation.Nullable map[string]interface{} TransferMedia) {
    this.TransferMedia = TransferMedia;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceMenuOutputFullMedia ServiceMenuOutputFullMedia = (ServiceMenuOutputFullMedia) o;
    return Objects.equals(this.Greeting, ServiceMenuOutputFullMedia.Greeting) &&
        Objects.equals(this.InvalidMedia, ServiceMenuOutputFullMedia.InvalidMedia) &&
        Objects.equals(this.TransferMedia, ServiceMenuOutputFullMedia.TransferMedia);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Greeting, InvalidMedia, TransferMedia);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceMenuOutputFullMedia {\n");
    sb.append("    Greeting: ").append(toIndentedString(Greeting)).append("\n");
    sb.append("    InvalidMedia: ").append(toIndentedString(InvalidMedia)).append("\n");
    sb.append("    TransferMedia: ").append(toIndentedString(TransferMedia)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

