/*
White Label Communications CPaas API Documentation

A CPaaS platform API

API version: 1.1
Contact: support@whitelabelcomm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServiceCallQueueOutputFull type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceCallQueueOutputFull{}

// ServiceCallQueueOutputFull struct for ServiceCallQueueOutputFull
type ServiceCallQueueOutputFull struct {
	AgentWrapupTime *int32 `json:"agent_wrapup_time,omitempty"`
	Features map[string]interface{} `json:"features,omitempty"`
	ForceAwayOnReject *bool `json:"force_away_on_reject,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	QueueRouter *string `json:"queue_router,omitempty"`
	QueueType *string `json:"queue_type,omitempty"`
	RingTimeout *int32 `json:"ring_timeout,omitempty"`
	TickTime *int32 `json:"tick_time,omitempty"`
}

// NewServiceCallQueueOutputFull instantiates a new ServiceCallQueueOutputFull object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceCallQueueOutputFull() *ServiceCallQueueOutputFull {
	this := ServiceCallQueueOutputFull{}
	return &this
}

// NewServiceCallQueueOutputFullWithDefaults instantiates a new ServiceCallQueueOutputFull object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceCallQueueOutputFullWithDefaults() *ServiceCallQueueOutputFull {
	this := ServiceCallQueueOutputFull{}
	return &this
}

// GetAgentWrapupTime returns the AgentWrapupTime field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputFull) GetAgentWrapupTime() int32 {
	if o == nil || IsNil(o.AgentWrapupTime) {
		var ret int32
		return ret
	}
	return *o.AgentWrapupTime
}

// GetAgentWrapupTimeOk returns a tuple with the AgentWrapupTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputFull) GetAgentWrapupTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.AgentWrapupTime) {
		return nil, false
	}
	return o.AgentWrapupTime, true
}

// HasAgentWrapupTime returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputFull) HasAgentWrapupTime() bool {
	if o != nil && !IsNil(o.AgentWrapupTime) {
		return true
	}

	return false
}

// SetAgentWrapupTime gets a reference to the given int32 and assigns it to the AgentWrapupTime field.
func (o *ServiceCallQueueOutputFull) SetAgentWrapupTime(v int32) {
	o.AgentWrapupTime = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputFull) GetFeatures() map[string]interface{} {
	if o == nil || IsNil(o.Features) {
		var ret map[string]interface{}
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputFull) GetFeaturesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Features) {
		return map[string]interface{}{}, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputFull) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given map[string]interface{} and assigns it to the Features field.
func (o *ServiceCallQueueOutputFull) SetFeatures(v map[string]interface{}) {
	o.Features = v
}

// GetForceAwayOnReject returns the ForceAwayOnReject field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputFull) GetForceAwayOnReject() bool {
	if o == nil || IsNil(o.ForceAwayOnReject) {
		var ret bool
		return ret
	}
	return *o.ForceAwayOnReject
}

// GetForceAwayOnRejectOk returns a tuple with the ForceAwayOnReject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputFull) GetForceAwayOnRejectOk() (*bool, bool) {
	if o == nil || IsNil(o.ForceAwayOnReject) {
		return nil, false
	}
	return o.ForceAwayOnReject, true
}

// HasForceAwayOnReject returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputFull) HasForceAwayOnReject() bool {
	if o != nil && !IsNil(o.ForceAwayOnReject) {
		return true
	}

	return false
}

// SetForceAwayOnReject gets a reference to the given bool and assigns it to the ForceAwayOnReject field.
func (o *ServiceCallQueueOutputFull) SetForceAwayOnReject(v bool) {
	o.ForceAwayOnReject = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputFull) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputFull) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputFull) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ServiceCallQueueOutputFull) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputFull) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputFull) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputFull) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceCallQueueOutputFull) SetName(v string) {
	o.Name = &v
}

// GetQueueRouter returns the QueueRouter field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputFull) GetQueueRouter() string {
	if o == nil || IsNil(o.QueueRouter) {
		var ret string
		return ret
	}
	return *o.QueueRouter
}

// GetQueueRouterOk returns a tuple with the QueueRouter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputFull) GetQueueRouterOk() (*string, bool) {
	if o == nil || IsNil(o.QueueRouter) {
		return nil, false
	}
	return o.QueueRouter, true
}

// HasQueueRouter returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputFull) HasQueueRouter() bool {
	if o != nil && !IsNil(o.QueueRouter) {
		return true
	}

	return false
}

// SetQueueRouter gets a reference to the given string and assigns it to the QueueRouter field.
func (o *ServiceCallQueueOutputFull) SetQueueRouter(v string) {
	o.QueueRouter = &v
}

// GetQueueType returns the QueueType field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputFull) GetQueueType() string {
	if o == nil || IsNil(o.QueueType) {
		var ret string
		return ret
	}
	return *o.QueueType
}

// GetQueueTypeOk returns a tuple with the QueueType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputFull) GetQueueTypeOk() (*string, bool) {
	if o == nil || IsNil(o.QueueType) {
		return nil, false
	}
	return o.QueueType, true
}

// HasQueueType returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputFull) HasQueueType() bool {
	if o != nil && !IsNil(o.QueueType) {
		return true
	}

	return false
}

// SetQueueType gets a reference to the given string and assigns it to the QueueType field.
func (o *ServiceCallQueueOutputFull) SetQueueType(v string) {
	o.QueueType = &v
}

// GetRingTimeout returns the RingTimeout field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputFull) GetRingTimeout() int32 {
	if o == nil || IsNil(o.RingTimeout) {
		var ret int32
		return ret
	}
	return *o.RingTimeout
}

// GetRingTimeoutOk returns a tuple with the RingTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputFull) GetRingTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.RingTimeout) {
		return nil, false
	}
	return o.RingTimeout, true
}

// HasRingTimeout returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputFull) HasRingTimeout() bool {
	if o != nil && !IsNil(o.RingTimeout) {
		return true
	}

	return false
}

// SetRingTimeout gets a reference to the given int32 and assigns it to the RingTimeout field.
func (o *ServiceCallQueueOutputFull) SetRingTimeout(v int32) {
	o.RingTimeout = &v
}

// GetTickTime returns the TickTime field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputFull) GetTickTime() int32 {
	if o == nil || IsNil(o.TickTime) {
		var ret int32
		return ret
	}
	return *o.TickTime
}

// GetTickTimeOk returns a tuple with the TickTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputFull) GetTickTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.TickTime) {
		return nil, false
	}
	return o.TickTime, true
}

// HasTickTime returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputFull) HasTickTime() bool {
	if o != nil && !IsNil(o.TickTime) {
		return true
	}

	return false
}

// SetTickTime gets a reference to the given int32 and assigns it to the TickTime field.
func (o *ServiceCallQueueOutputFull) SetTickTime(v int32) {
	o.TickTime = &v
}

func (o ServiceCallQueueOutputFull) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceCallQueueOutputFull) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentWrapupTime) {
		toSerialize["agent_wrapup_time"] = o.AgentWrapupTime
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.ForceAwayOnReject) {
		toSerialize["force_away_on_reject"] = o.ForceAwayOnReject
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.QueueRouter) {
		toSerialize["queue_router"] = o.QueueRouter
	}
	if !IsNil(o.QueueType) {
		toSerialize["queue_type"] = o.QueueType
	}
	if !IsNil(o.RingTimeout) {
		toSerialize["ring_timeout"] = o.RingTimeout
	}
	if !IsNil(o.TickTime) {
		toSerialize["tick_time"] = o.TickTime
	}
	return toSerialize, nil
}

type NullableServiceCallQueueOutputFull struct {
	value *ServiceCallQueueOutputFull
	isSet bool
}

func (v NullableServiceCallQueueOutputFull) Get() *ServiceCallQueueOutputFull {
	return v.value
}

func (v *NullableServiceCallQueueOutputFull) Set(val *ServiceCallQueueOutputFull) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceCallQueueOutputFull) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceCallQueueOutputFull) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceCallQueueOutputFull(val *ServiceCallQueueOutputFull) *NullableServiceCallQueueOutputFull {
	return &NullableServiceCallQueueOutputFull{value: val, isSet: true}
}

func (v NullableServiceCallQueueOutputFull) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceCallQueueOutputFull) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


