/*
White Label Communications CPaas API Documentation

A CPaaS platform API

API version: 1.1
Contact: support@whitelabelcomm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServiceAccountOutputFullCalleridExternal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountOutputFullCalleridExternal{}

// ServiceAccountOutputFullCalleridExternal struct for ServiceAccountOutputFullCalleridExternal
type ServiceAccountOutputFullCalleridExternal struct {
	Number *string `json:"number,omitempty"`
}

// NewServiceAccountOutputFullCalleridExternal instantiates a new ServiceAccountOutputFullCalleridExternal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountOutputFullCalleridExternal() *ServiceAccountOutputFullCalleridExternal {
	this := ServiceAccountOutputFullCalleridExternal{}
	return &this
}

// NewServiceAccountOutputFullCalleridExternalWithDefaults instantiates a new ServiceAccountOutputFullCalleridExternal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountOutputFullCalleridExternalWithDefaults() *ServiceAccountOutputFullCalleridExternal {
	this := ServiceAccountOutputFullCalleridExternal{}
	return &this
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *ServiceAccountOutputFullCalleridExternal) GetNumber() string {
	if o == nil || IsNil(o.Number) {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountOutputFullCalleridExternal) GetNumberOk() (*string, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *ServiceAccountOutputFullCalleridExternal) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *ServiceAccountOutputFullCalleridExternal) SetNumber(v string) {
	o.Number = &v
}

func (o ServiceAccountOutputFullCalleridExternal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountOutputFullCalleridExternal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	return toSerialize, nil
}

type NullableServiceAccountOutputFullCalleridExternal struct {
	value *ServiceAccountOutputFullCalleridExternal
	isSet bool
}

func (v NullableServiceAccountOutputFullCalleridExternal) Get() *ServiceAccountOutputFullCalleridExternal {
	return v.value
}

func (v *NullableServiceAccountOutputFullCalleridExternal) Set(val *ServiceAccountOutputFullCalleridExternal) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountOutputFullCalleridExternal) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountOutputFullCalleridExternal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountOutputFullCalleridExternal(val *ServiceAccountOutputFullCalleridExternal) *NullableServiceAccountOutputFullCalleridExternal {
	return &NullableServiceAccountOutputFullCalleridExternal{value: val, isSet: true}
}

func (v NullableServiceAccountOutputFullCalleridExternal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountOutputFullCalleridExternal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


