/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapi;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceCampaignPhoneNumberOutput
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.GoClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceCampaignPhoneNumberOutput {
  @.annotation.Nullable
  private []string TelephoneNumbers;

  @.annotation.Nullable
  private int32 TotalCount;

  public ServiceCampaignPhoneNumberOutput() {
  }

  public ServiceCampaignPhoneNumberOutput TelephoneNumbers(@.annotation.Nullable []string TelephoneNumbers) {
    
    this.TelephoneNumbers = TelephoneNumbers;
    return this;
  }

  public ServiceCampaignPhoneNumberOutput addTelephoneNumbersItem(string TelephoneNumbersItem) {
    if (this.TelephoneNumbers == null) {
      this.TelephoneNumbers = new ArrayList<>();
    }
    this.TelephoneNumbers.add(TelephoneNumbersItem);
    return this;
  }

  /**
   * Get TelephoneNumbers
   * @return TelephoneNumbers
   */
  @.annotation.Nullable

  public []string GetTelephoneNumbers() {
    return TelephoneNumbers;
  }


  public void setTelephoneNumbers(@.annotation.Nullable []string TelephoneNumbers) {
    this.TelephoneNumbers = TelephoneNumbers;
  }

  public ServiceCampaignPhoneNumberOutput TotalCount(@.annotation.Nullable int32 TotalCount) {
    
    this.TotalCount = TotalCount;
    return this;
  }

  /**
   * Get TotalCount
   * @return TotalCount
   */
  @.annotation.Nullable

  public int32 GetTotalCount() {
    return TotalCount;
  }


  public void setTotalCount(@.annotation.Nullable int32 TotalCount) {
    this.TotalCount = TotalCount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceCampaignPhoneNumberOutput ServiceCampaignPhoneNumberOutput = (ServiceCampaignPhoneNumberOutput) o;
    return Objects.equals(this.TelephoneNumbers, ServiceCampaignPhoneNumberOutput.TelephoneNumbers) &&
        Objects.equals(this.TotalCount, ServiceCampaignPhoneNumberOutput.TotalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(TelephoneNumbers, TotalCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceCampaignPhoneNumberOutput {\n");
    sb.append("    TelephoneNumbers: ").append(toIndentedString(TelephoneNumbers)).append("\n");
    sb.append("    TotalCount: ").append(toIndentedString(TotalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

