/*
White Label Communications CPaas API Documentation

A CPaaS platform API

API version: 1.1
Contact: support@whitelabelcomm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServiceGroupOutputFull type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceGroupOutputFull{}

// ServiceGroupOutputFull struct for ServiceGroupOutputFull
type ServiceGroupOutputFull struct {
	Endpoints *map[string]ServiceEndpoint `json:"endpoints,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewServiceGroupOutputFull instantiates a new ServiceGroupOutputFull object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceGroupOutputFull() *ServiceGroupOutputFull {
	this := ServiceGroupOutputFull{}
	return &this
}

// NewServiceGroupOutputFullWithDefaults instantiates a new ServiceGroupOutputFull object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceGroupOutputFullWithDefaults() *ServiceGroupOutputFull {
	this := ServiceGroupOutputFull{}
	return &this
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise.
func (o *ServiceGroupOutputFull) GetEndpoints() map[string]ServiceEndpoint {
	if o == nil || IsNil(o.Endpoints) {
		var ret map[string]ServiceEndpoint
		return ret
	}
	return *o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceGroupOutputFull) GetEndpointsOk() (*map[string]ServiceEndpoint, bool) {
	if o == nil || IsNil(o.Endpoints) {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *ServiceGroupOutputFull) HasEndpoints() bool {
	if o != nil && !IsNil(o.Endpoints) {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given map[string]ServiceEndpoint and assigns it to the Endpoints field.
func (o *ServiceGroupOutputFull) SetEndpoints(v map[string]ServiceEndpoint) {
	o.Endpoints = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServiceGroupOutputFull) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceGroupOutputFull) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServiceGroupOutputFull) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ServiceGroupOutputFull) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceGroupOutputFull) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceGroupOutputFull) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceGroupOutputFull) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceGroupOutputFull) SetName(v string) {
	o.Name = &v
}

func (o ServiceGroupOutputFull) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceGroupOutputFull) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Endpoints) {
		toSerialize["endpoints"] = o.Endpoints
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableServiceGroupOutputFull struct {
	value *ServiceGroupOutputFull
	isSet bool
}

func (v NullableServiceGroupOutputFull) Get() *ServiceGroupOutputFull {
	return v.value
}

func (v *NullableServiceGroupOutputFull) Set(val *ServiceGroupOutputFull) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceGroupOutputFull) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceGroupOutputFull) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceGroupOutputFull(val *ServiceGroupOutputFull) *NullableServiceGroupOutputFull {
	return &NullableServiceGroupOutputFull{value: val, isSet: true}
}

func (v NullableServiceGroupOutputFull) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceGroupOutputFull) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


