/*
White Label Communications CPaas API Documentation

A CPaaS platform API

API version: 1.1
Contact: support@whitelabelcomm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServiceCallQueueOutputShort type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceCallQueueOutputShort{}

// ServiceCallQueueOutputShort struct for ServiceCallQueueOutputShort
type ServiceCallQueueOutputShort struct {
	Features map[string]interface{} `json:"features,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewServiceCallQueueOutputShort instantiates a new ServiceCallQueueOutputShort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceCallQueueOutputShort() *ServiceCallQueueOutputShort {
	this := ServiceCallQueueOutputShort{}
	return &this
}

// NewServiceCallQueueOutputShortWithDefaults instantiates a new ServiceCallQueueOutputShort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceCallQueueOutputShortWithDefaults() *ServiceCallQueueOutputShort {
	this := ServiceCallQueueOutputShort{}
	return &this
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputShort) GetFeatures() map[string]interface{} {
	if o == nil || IsNil(o.Features) {
		var ret map[string]interface{}
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputShort) GetFeaturesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Features) {
		return map[string]interface{}{}, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputShort) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given map[string]interface{} and assigns it to the Features field.
func (o *ServiceCallQueueOutputShort) SetFeatures(v map[string]interface{}) {
	o.Features = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputShort) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputShort) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputShort) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ServiceCallQueueOutputShort) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceCallQueueOutputShort) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceCallQueueOutputShort) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceCallQueueOutputShort) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceCallQueueOutputShort) SetName(v string) {
	o.Name = &v
}

func (o ServiceCallQueueOutputShort) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceCallQueueOutputShort) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableServiceCallQueueOutputShort struct {
	value *ServiceCallQueueOutputShort
	isSet bool
}

func (v NullableServiceCallQueueOutputShort) Get() *ServiceCallQueueOutputShort {
	return v.value
}

func (v *NullableServiceCallQueueOutputShort) Set(val *ServiceCallQueueOutputShort) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceCallQueueOutputShort) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceCallQueueOutputShort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceCallQueueOutputShort(val *ServiceCallQueueOutputShort) *NullableServiceCallQueueOutputShort {
	return &NullableServiceCallQueueOutputShort{value: val, isSet: true}
}

func (v NullableServiceCallQueueOutputShort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceCallQueueOutputShort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


