/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapi;

import java.util.Objects;
import java.util.Arrays;

/**
 * ModelAccountSummaryByDate
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.GoClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ModelAccountSummaryByDate {
  @.annotation.Nullable
  private float32 Cost;

  @.annotation.Nullable
  private string Date;

  @.annotation.Nullable
  private int32 TransactionCount;

  public ModelAccountSummaryByDate() {
  }

  public ModelAccountSummaryByDate Cost(@.annotation.Nullable float32 Cost) {
    
    this.Cost = Cost;
    return this;
  }

  /**
   * Get Cost
   * @return Cost
   */
  @.annotation.Nullable

  public float32 GetCost() {
    return Cost;
  }


  public void setCost(@.annotation.Nullable float32 Cost) {
    this.Cost = Cost;
  }

  public ModelAccountSummaryByDate Date(@.annotation.Nullable string Date) {
    
    this.Date = Date;
    return this;
  }

  /**
   * Get Date
   * @return Date
   */
  @.annotation.Nullable

  public string GetDate() {
    return Date;
  }


  public void setDate(@.annotation.Nullable string Date) {
    this.Date = Date;
  }

  public ModelAccountSummaryByDate TransactionCount(@.annotation.Nullable int32 TransactionCount) {
    
    this.TransactionCount = TransactionCount;
    return this;
  }

  /**
   * Get TransactionCount
   * @return TransactionCount
   */
  @.annotation.Nullable

  public int32 GetTransactionCount() {
    return TransactionCount;
  }


  public void setTransactionCount(@.annotation.Nullable int32 TransactionCount) {
    this.TransactionCount = TransactionCount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelAccountSummaryByDate ModelAccountSummaryByDate = (ModelAccountSummaryByDate) o;
    return Objects.equals(this.Cost, ModelAccountSummaryByDate.Cost) &&
        Objects.equals(this.Date, ModelAccountSummaryByDate.Date) &&
        Objects.equals(this.TransactionCount, ModelAccountSummaryByDate.TransactionCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Cost, Date, TransactionCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelAccountSummaryByDate {\n");
    sb.append("    Cost: ").append(toIndentedString(Cost)).append("\n");
    sb.append("    Date: ").append(toIndentedString(Date)).append("\n");
    sb.append("    TransactionCount: ").append(toIndentedString(TransactionCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

