/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapi;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceDeviceOutputFullCalleridExternal
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.GoClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceDeviceOutputFullCalleridExternal {
  @.annotation.Nullable
  private string Number;

  public ServiceDeviceOutputFullCalleridExternal() {
  }

  public ServiceDeviceOutputFullCalleridExternal Number(@.annotation.Nullable string Number) {
    
    this.Number = Number;
    return this;
  }

  /**
   * Get Number
   * @return Number
   */
  @.annotation.Nullable

  public string GetNumber() {
    return Number;
  }


  public void setNumber(@.annotation.Nullable string Number) {
    this.Number = Number;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceDeviceOutputFullCalleridExternal ServiceDeviceOutputFullCalleridExternal = (ServiceDeviceOutputFullCalleridExternal) o;
    return Objects.equals(this.Number, ServiceDeviceOutputFullCalleridExternal.Number);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Number);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceDeviceOutputFullCalleridExternal {\n");
    sb.append("    Number: ").append(toIndentedString(Number)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

