/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapi;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceVOIPVoicemailMessageChange
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.GoClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceVOIPVoicemailMessageChange {
  /**
   * Gets or Sets Folder
   */
  public enum FOLDER {
    DELETED(string.valueOf("deleted")),
    
    SAVED(string.valueOf("saved")),
    
    NEW(string.valueOf("new"));

    private string value;

    FOLDER(string value) {
      this.value = value;
    }

    public string getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FOLDER fromValue(string value) {
      for (FOLDER b : FOLDER.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @.annotation.Nullable
  private FOLDER Folder;

  @.annotation.Nullable
  private map[string]interface{} SourceId;

  public ServiceVOIPVoicemailMessageChange() {
  }

  public ServiceVOIPVoicemailMessageChange Folder(@.annotation.Nullable FOLDER Folder) {
    
    this.Folder = Folder;
    return this;
  }

  /**
   * Get Folder
   * @return Folder
   */
  @.annotation.Nullable

  public FOLDER GetFolder() {
    return Folder;
  }


  public void setFolder(@.annotation.Nullable FOLDER Folder) {
    this.Folder = Folder;
  }

  public ServiceVOIPVoicemailMessageChange SourceId(@.annotation.Nullable map[string]interface{} SourceId) {
    
    this.SourceId = SourceId;
    return this;
  }

  /**
   * Get SourceId
   * @return SourceId
   */
  @.annotation.Nullable

  public map[string]interface{} GetSourceId() {
    return SourceId;
  }


  public void setSourceId(@.annotation.Nullable map[string]interface{} SourceId) {
    this.SourceId = SourceId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPVoicemailMessageChange ServiceVOIPVoicemailMessageChange = (ServiceVOIPVoicemailMessageChange) o;
    return Objects.equals(this.Folder, ServiceVOIPVoicemailMessageChange.Folder) &&
        Objects.equals(this.SourceId, ServiceVOIPVoicemailMessageChange.SourceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Folder, SourceId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPVoicemailMessageChange {\n");
    sb.append("    Folder: ").append(toIndentedString(Folder)).append("\n");
    sb.append("    SourceId: ").append(toIndentedString(SourceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

